[package]
name = "basecamp_04_demo"
version = "0.1.0"
description = "Workshop to learn the basics of testing a contract."
homepage = ""

[dependencies]

[scripts]
test = "cairo-test --starknet ."
test_single= "cairo-test --starknet . -f"

[[target.starknet-contract]]
